cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "caskroom/drivers"

brew "ansible"
brew "bash-completion"
brew "bash"
brew "git"
brew "go"
brew "htop"
brew "nmap"
brew "node"
brew "packer"
brew "terraform"
brew "watch"
brew "wget"
brew "youtube-dl"

cask "1password"
cask "bettertouchtool"
cask "cyberduck"
cask "disk-inventory-x"
cask "docker"
cask "dropbox"
cask "etcher" 
cask "google-backup-and-sync"
cask "google-chrome"
cask "gotomeeting"
cask "hp-easy-start"
cask "istat-menus"
cask "iterm2"
cask "postico"
cask "postman"
cask "pritunl"
cask "skype"
cask "slack"
cask "soulver"
cask "spotify"
cask "the-unarchiver"
cask "transmission"
cask "vagrant"
cask "vanilla"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
