# Path to the bash it configuration
export BASH_IT="/Users/james/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export BASH_IT_THEME='hawaii50'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Load Bash It
source "$BASH_IT"/bash_it.sh

# gcloud
source ~/google-cloud-sdk/completion.bash.inc
source ~/google-cloud-sdk/path.bash.inc

# Python
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
